### ISSUE TITLE
Automation dropdown menu and preference issues

### ISSUE THREAD

**Issue by bw352** [ksalzke/follow-up-task-omnifocus-plugin#2]
The "Omni Automation" dropdowns on Mac and iOS show the folder name as "com.KaitlinSalzke.followUpTask"

"Preferences: Follow-Up Tasks" does not work for me on Mac or iOS.

I am running the latest OF 4 betas and current non-beta operating systems.

**Comment by ksalzke** [comment]
Thanks @bw352 - should both be fixed now.

This plug-in is still a bit of a work in progress as I'm sure you can tell. :-)
